### ISSUE TITLE
mention of your work on the guide

### ISSUE THREAD

**Issue by wanesty** [lf-/affinity-crimes#5]
hey! i've moved the guide to a vuepress based website for readability, it has a more documentation style ui now.

anyhow i've been wanting add a mention of your work here on it even before moving to vuepress but i don't exactly know how i want to do it so i've been putting it off.

if you have an idea of how you'd want it to be presented on there, you're welcome to make a pr on codeberg or simply tell me here :p

**Comment by lf-** [comment]
I think it might be best presented as: "there is an easy, scripted, fully reproducible setup with nix", or something like that.

**Comment by wanesty** [comment]
[done](https://codeberg.org/wanesty/affinity-wine-docs/commit/10c82a3b292b3a9a5ef706770978cec09af71760)

> - If you happen to use [NixOS](https://nixos.org/) you probably want to look at [affinity crimes](https://github.com/lf-/affinity-crimes) on github, it aims to offer an easy, scripted and fully reproducible setup with nix.

i let you close this issue if you find it satisfactory :p

**Comment by lf-** [comment]
Should not say NixOS, but nix instead. It works on non NixOS with the appropriate graphics drivers wrapper.

**Comment by wanesty** [comment]
i assumed NixOS since i don't think i've ever seen/heard of anyone using the Nix pm outside of nixos but [done](https://codeberg.org/wanesty/affinity-wine-docs/commit/13807c9b0eb1e1891374e9e0c89571f3da580c7f):

> - If you happen to use [NixOS](https://nixos.org/) or the [Nix](https://github.com/NixOS/nix) package manager, you probably want to look at [affinity crimes](https://github.com/lf-/affinity-crimes) on github, it aims to offer an easy, scripted and fully reproducible setup with Nix.

**Comment by lf-** [comment]
nix works on every Linux distro and macOS, providing a valuable service of packages that aren't 2 years old on Debian, and avoiding using homebrew on macOS :)

it's a well supported use case, aside from the gpu driver LD_LIBRARY_PATH wrapper stuff required on Linux due to video drivers not being placed at the path NixOS puts them (this was done for decoupling the driver packages from mesa itself i think).

**Comment by wanesty** [comment]
i mean, i knew it was a package manager before being a distro,
i just **assumed** people wanting nix would just use nixOS completely, as i have never heard of anyone in recent years still using nix outside of nixOS

**Comment by lf-** [comment]
I develop one of the major Nix implementations. There's substantial numbers both on and off NixOS on Linux, and lots of Mac users, a small number of whom are adventurous enough to use nix-darwin for declarative macOS configuration. I don't have actual numbers because we don't collect telemetry, but we regularly talk to users on all these platforms.

anyhow, lgtm
